### PR TITLE
Move SYCL-related functionality to internal

### PR DESCRIPTION
**Pull request by rlnx**
Summary of changes:
- Directory `include/sycl/internal` -> `include/services/internal/sycl`
- Namespace `oneapi::internal` -> `services::internal::sycl`
- Move tables and execution contexts to `internal` namespace
- Updated examples

### CODE REVIEW

**Comment by rlnx** [comment]
@michael-smirnov, @napetrov, it's strange to see daal4py tests passed. I've changed namespace of the public SYCL extensions, so oneapi part of daal4py should not build.

**Comment by napetrov** [comment]
we are not building oneapi part in this ci

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil/rename-sycl-ns

**Comment by napetrov** [comment]
/intelci: restart
set infra_branch=dev/risrafil/rename-sycl-ns

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil/rename-sycl-ns

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil/rename-sycl-ns

**Review by makart19 — APPROVED** [review]

**Comment by napetrov** [comment]
/intelci: run
set infra_branch=dev/risrafil/rename-sycl-ns

**Review by napetrov — APPROVED** [review]

**Pull request merged**
