### PR TITLE
Repository restructure

### PR DESCRIPTION
**Pull request by rlnx**
Draft Pull request to check if restructured repository infrastructure works as expected

### CODE REVIEW

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: restart
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: restart
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by napetrov** [comment]
.ci/pipeline/docs.yml  should be updated with new paths to include docs and examples

**Comment by rlnx** [comment]
> .ci/pipeline/docs.yml should be updated with new paths to include docs and examples

@napetrov, I can figure out only one change: `include` -> `cpp/daal/include`

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by averbukh** [comment]
For this particular PR, it's highly important to merge it is such a way to preserve files history (to have file renaming in separate commits)

**Comment by napetrov** [comment]
INSTALL.md should be updated to reflect new mkl/tbb download scripts names 

> 
> 
> > .ci/pipeline/docs.yml should be updated with new paths to include docs and examples
> 
> @napetrov, I can figure out only one change: `include` -> `cpp/daal/include`

yes.  As for examples - i think that then this should be updated in  docs/rst_examples.py   - script assumes old paths for documentation build

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-restructure-draft

**Comment by rlnx** [comment]
All checks are passed: https://ecmd.inn.intel.com/commander/link/jobDetails/jobs/eaabeac9-657d-f1f4-ae80-8cdcd4b723a1

**Pull request closed without merging**
