### PR TITLE
SVM for regression task

### PR DESCRIPTION
**Pull request by PetrovKP**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by napetrov** [comment]
@PetrovKP  - do we need this request?

**Comment by PetrovKP** [comment]
> @PetrovKP - do we need this request?

I would leave this PR - it will be useful to me.

**Comment by napetrov** [comment]
@vlad-nazarov  - do you need this PR?

**Comment by vlad-nazarov** [comment]
@napetrov, I think we can close this

**Pull request closed without merging**
