### PR TITLE
Fix exports in FPK on Windows

### PR DESCRIPTION
**Pull request by Alexsandruss**
Add missing symbols to mklfpk on Windows.

### CODE REVIEW

**Comment by Alexsandruss** [comment]
Combined CI job with https://github.com/intel/scikit-learn-intelex/pull/1699: http://intel-ci.intel.com/eec606f5-57f6-f156-956b-a4bf010d0e2e

**Review by Alexandr-Solovev — APPROVED** [review]
LGTM, please lets wait the result of public ci steps

**Review by ethanglaser — APPROVED** [review]

**Comment by Alexsandruss** [comment]
@Mergifyio backport rls/2024.2.0-rls

**Pull request merged**
