### PR TITLE
FIX: sycl barrier() deprecation alternative

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by ethanglaser** [comment]
CEV with branch: http://intel-ci.intel.com/eef206c3-8f06-f149-a0b1-a4bf010d0e2e
Compared to last nightly: http://intel-ci.intel.com/eef15de1-40d8-f1c7-8447-a4bf010d0e2e

**Review by Alexandr-Solovev — APPROVED** [review]
LGTM! Please doublecheck that CI is green, and can you please additionally launch onedal-benchmarks with these changes to clarify that there are no degradations

**Pull request merged**
