### PR TITLE
Enable DPC++ support in daal4py

### PR DESCRIPTION
**Pull request by napetrov**

### CODE REVIEW

**Comment by napetrov** [comment]
@vlad-nazarov  - we need new mklfpk gpu to make this green. Let's wait for release and try uploading new fpk.

**Review by michael-smirnov — APPROVED** [review]

**Comment by napetrov** [comment]
@Mergifyio rebase

**Review by Pahandrovich — APPROVED** [review]

**Review by KulikovNikita — APPROVED** [review]

**Pull request merged**
