### PR TITLE
Adjust modulefile according to the requirements

### PR DESCRIPTION
**Pull request by maria-Petrova**
The PR addresses the most recent changes in the modulefile.

### CODE REVIEW

**Comment by ethanglaser** [comment]
Can this be closed now that it is resolved in release branch?

**Comment by napetrov** [comment]
we need some fix here anyway as we can't drop this internally with current state. 

If there is no simple fix now we can just don't have ARM modulefiles for now

**Comment by ethanglaser** [comment]
Duplicate of https://github.com/oneapi-src/oneDAL/pull/2823

**Pull request closed without merging**
