### PR TITLE
update version to 2024.1.0

### PR DESCRIPTION
**Pull request by md-shafiul-alam**

### CODE REVIEW

**Review by napetrov — APPROVED** [review]
Assuming CI would pass

**Review by ethanglaser — APPROVED** [review]
Let's merge https://github.com/intel/scikit-learn-intelex/pull/1629 and re-run public CI here - it should be green. Internal CI is good when ran with those changes (http://intel-ci.intel.com/eea9bba7-ed01-f15b-bf74-a4bf010d0e2e)

**Comment by md-shafiul-alam** [comment]
all green except the timeout issues, which is supposed to be fixed with https://github.com/intel/scikit-learn-intelex/pull/1633

**Pull request merged**
