### PR TITLE
Update security md

### PR DESCRIPTION
**Pull request by emmwalsh**
Updated SECURITY.md file as requested by Nikolay Petrov

### CODE REVIEW

**Comment by emmwalsh** [comment]
@bdmoore1 can you review and approve this please? Thanks

**Review by emmwalsh — COMMENTED** [review]
@bdmoore1

**Review by bdmoore1 — APPROVED** [review]
Looks good to me.

**Review by bdmoore1 — CHANGES_REQUESTED** [review]
Remove all of the asterisks after Library. The asterisk is to signify a 3rd party brand name. Scikit-learn is a 3rd party brand name, so that's why it was there before. But oneDAL is Intel's brand name so we brand it with (R) and (TM).

**Comment by maria-Petrova** [comment]
I'll approve the PR once Ben's comments are addressed.

**Comment by emmwalsh** [comment]
> I'll approve the PR once Ben's comments are addressed.

Hi @maria-Petrova I have removed the asterisk and have resolved Bens Comments :)

**Review by maria-Petrova — APPROVED** [review]

**Comment by rozhukov** [comment]
Hi @maria-Petrova @emmwalsh , I noticed you've made updates to security.md, which is good. I see a few issues/typos:
1. Please remove Intel wording from all the text as it's now officially UXL
2. Link is broken here: 
_Report a vulnerability to us in one of two ways:
Open a draft [GitHub Security Advisory][2]*_
3. Link is broken here: 
_Disclosure Policy
We will publish security advisories using the [GitHub Security Advisories feature][3]_

**Comment by emmwalsh** [comment]
> Hi @maria-Petrova @emmwalsh , I noticed you've made updates to security.md, which is good. I see a few issues/typos:
> 
> 1. Please remove Intel wording from all the text as it's now officially UXL
> 2. Link is broken here:
>    _Report a vulnerability to us in one of two ways:
>    Open a draft [GitHub Security Advisory][2]*_
> 3. Link is broken here:
>    _Disclosure Policy
>    We will publish security advisories using the [GitHub Security Advisories feature][3]_
Hi @rozhukov should I replace the Intel wording with UXL or just remove the Intel wording with no replacement? Thanks

**Comment by rozhukov** [comment]
> > Hi @maria-Petrova @emmwalsh , I noticed you've made updates to security.md, which is good. I see a few issues/typos:
> > 
> > 1. Please remove Intel wording from all the text as it's now officially UXL
> > 2. Link is broken here:
> >    _Report a vulnerability to us in one of two ways:
> >    Open a draft [GitHub Security Advisory][2]*_
> > 3. Link is broken here:
> >    _Disclosure Policy
> >    We will publish security advisories using the [GitHub Security Advisories feature][3]_
> >    Hi @rozhukov should I replace the Intel wording with UXL or just remove the Intel wording with no replacement? Thanks

It's up to you. I'd suggest to keep it independent like simply "oneDAL". 
Example: https://github.com/oneapi-src/oneDNN/blob/main/SECURITY.md

**Comment by emmwalsh** [comment]
Hi @rozhukov I have made the changes now but for the third point, do you know what the correct link is or should I just remove the link and not replace it with anything? Thanks!

**Comment by rozhukov** [comment]
> Hi @rozhukov I have made the changes now but for the third point, do you know what the correct link is or should I just remove the link and not replace it with anything? Thanks!

just link is broken itself in the markdown
image

It should lead to the respective "Report vulnerability" button: https://github.com/oneapi-src/oneDAL/security/advisories/new

**Comment by emmwalsh** [comment]
Hi @rozhukov, thanks so much for that! I have updated the second link now. For the third link under the disclosure policy, do you know what the link should be for [**GitHub Security Advisories feature**][3]?

Thanks!

**Pull request merged**
