### PR TITLE
[Feature] Add multithreaded searches for all Decision Forest trees simultaneously

### PR DESCRIPTION
**Pull request by icfaust**
# Description
As of now, only single threaded DFS and BFS exist. This uses dal::detail::threader_for to make it run all trees simultaneously. This provides a speedup for Scikit-Learn-intelex RF preview.
Changes proposed in this pull request:
- Add new overloaded method for traverse_depth_first decision forest model (common.hpp)
- Add new overloaded method for traverse_breadth_first decision forest model (common.hpp)
- Add header to dal threading to decision forest common.hpp

### CODE REVIEW

**Comment by Alexsandruss** [comment]
Common PreCommit job with https://github.com/intel/scikit-learn-intelex/pull/1333: http://intel-ci.intel.com/ee459771-cca8-f11a-93c5-a4bf010d0e2e

**Review by Alexsandruss — APPROVED** [review]

**Review by KulikovNikita — APPROVED** [review]
This is a very rough implementation. So I hope it will be revisited later

**Pull request merged**
