### PR TITLE
Enable MD flag for windows

### PR DESCRIPTION
**Pull request by Pahandrovich**

### CODE REVIEW

**Comment by Pahandrovich** [comment]
CI
http://intel-ci.intel.com/ebbced37-9bcb-f15d-8f29-8cdcd4b723a1

**Comment by Pahandrovich** [comment]
CI 2
http://intel-ci.intel.com/ebbd5c48-1a5c-f186-8a4c-8cdcd4b723a1

**Review by PetrovKP — APPROVED** [review]
After green CI

**Review by owerbat — APPROVED** [review]

**Comment by Pahandrovich** [comment]
CI 4
http://intel-ci.intel.com/jobs/ebbe0aed-87ea-f18c-badf-8cdcd4b723a1

**Pull request merged**
