### PR TITLE
Intel_LLVM compiler macros

### PR DESCRIPTION
**Pull request by napetrov**
# Description
Update intel compiler macros checks with Intel_LLVM case for migration to ICX compiler

### CODE REVIEW

**Review by KulikovNikita — APPROVED** [review]

**Comment by KulikovNikita** [comment]
> r SVM tests in this case. - don't see how to fix this yet
> 
> FAILED: Build did NOT complete successfully //cpp/oneapi/dal/algo/svm:test_batch_dpc FAILED TO BUILD

I believe that another person is already working on fixing this problem.

**Comment by napetrov** [comment]
@KulikovNikita   fixed build of SVM here, but get test failure

**Pull request merged**
