### PR TITLE
Optimize rbf & linear kernel for SOA table result

### PR DESCRIPTION
**Pull request by PetrovKP**
Optimize rbf & linear kernel for SOA table result

### CODE REVIEW

**Comment by PetrovKP** [comment]
http://intel-ci.intel.com/eac05a1c-dd5c-f129-a92f-8cdcd4b723a1?

**Comment by PetrovKP** [comment]
opt: http://intel-ci.intel.com/eac06c52-1944-f1ed-9e76-8cdcd4b723a1?

**Comment by PetrovKP** [comment]
without avx512: http://intel-ci.intel.com/eac09e57-128a-f1ed-a469-8cdcd4b723a1?

**Comment by PetrovKP** [comment]
opt: http://intel-ci.intel.com/eac536aa-d78c-f179-90b9-8cdcd4b723a1

**Comment by PetrovKP** [comment]
nightly:  http://intel-ci.intel.com/eaf0981e-6bfc-f13a-90a3-8cdcd4b723a1?

**Comment by PetrovKP** [comment]
nightly: http://intel-ci.intel.com/eaf0993d-b621-f156-962e-8cdcd4b723a1?

**Comment by PetrovKP** [comment]
@owerbat , Please, review this PR

**Comment by PetrovKP** [comment]
nightly: http://intel-ci.intel.com/eaf1a9a6-a63a-f115-b234-8cdcd4b723a1?

**Review by owerbat — APPROVED** [review]

**Pull request merged**
