### PR TITLE
Fix illegal instructions on Windows

### PR DESCRIPTION
**Pull request by rlnx**
The problem is that on Windows Intel compiler replaces the `new BlockDescritptor<T>[n]` expression with the custom compiler-generated function that allocates and initializes all `BlockDesriptor` elements in the array. The function is compiled multiple times with different compiler options and behaves as C++ `inline` that leads to ODR violation. Some versions of that function being compiled for multiple CPUs contain AVX2 instructions. When user's application (in fact, example or test system) is linked statically against DAL, the linker selects 'wrong' version of the function (the one which contains AVX2) that leads to 'illegal' instruction on old architectures.

The fix consists in moving `new BlockDescritptor<T>[n]` to separate object file that will be compiled once to satisfy ODR. Additionally, it introduces `BlockDescriptorArray` that simplifies resource management and fixes possible memory leaks in the existing decision tree code.

### CODE REVIEW

**Comment by PetrovKP** [comment]
As far as I remember, PCA tests failed. Why is it fixed in the DF?

**Comment by PetrovKP** [comment]
Do we really have a fails for DF?

**Comment by rlnx** [comment]
> Do we really have a fails for DF?

Not DF, but decision trees, which are used within (brow|ada|logit)boost. A lot of them: http://intel-ci.intel.com/eabef4d8-0ade-f150-a92f-8cdcd4b723a1, see `new_ts_bkw`

**Comment by PetrovKP** [comment]
Sorry, thanks! 😄

**Comment by rlnx** [comment]
new_ts_bkw is passed on Windows.

http://intel-ci.intel.com/eabf566e-e141-f13b-a8ca-8cdcd4b723a1

**Pull request merged**
