### PR TITLE
Increase major version of the default sycl library

### PR DESCRIPTION
**Pull request by maria-Petrova**
The PR aims to reflect a change of the major version of the default sycl library.

### CODE REVIEW

**Comment by maria-Petrova** [comment]
/intelci: run

set mac=0

set linux=0

**Comment by homksei** [comment]
/intelci: run
set mac=0
set linux=0

**Comment by homksei** [comment]
/intelci: run
set mac=0
set linux=0

**Comment by homksei** [comment]
/intelci: run
set mac=0

**Comment by homksei** [comment]
/intelci: run
set mac=0
set windows=0

**Review by homksei — APPROVED** [review]

**Pull request merged**
