### PR TITLE
kNN extension [rls/daal-2020-mnt]

### PR DESCRIPTION
**Pull request by Alexsandruss**
# Description
Extensions for k-Nearest Neighbors algorithm

Changes proposed in this pull request:
- brute-force method of algorithm
- kNN search

Merged copy of https://github.com/oneapi-src/oneDAL/pull/765 and https://github.com/oneapi-src/oneDAL/pull/776

### CODE REVIEW

**Review by SmirnovEgorRu — APPROVED** [review]

**Comment by Alexsandruss** [comment]
http://intel-ci.intel.com/eaf46877-4925-f198-9a01-8cdcd4b723a1

**Comment by Alexsandruss** [comment]
https://github.com/oneapi-src/oneDAL/pull/924 - constructor change from another PU is applied

**Comment by PetrovKP** [comment]
@averbukh  Do we want to see your changes https://github.com/oneapi-src/oneDAL/pull/928 in the release 2020u3?

**Comment by PetrovKP** [comment]
/intelci: restart
set infra_branch=dev/pyakovle-change-ipldt-file

**Comment by PetrovKP** [comment]
/intelci: restart
set infra_branch=dev/pyakovle-knn-remove-pydaal

**Comment by PetrovKP** [comment]
http://intel-ci.intel.com/eaf6b4ec-de01-f1a2-b434-8cdcd4b723a1?

**Comment by Alexsandruss** [comment]
> @averbukh Do we want to see your changes #928 in the release 2020u3?

Fix of #928 is added here.

**Comment by Alexsandruss** [comment]
CI of last fixes: http://intel-ci.intel.com/eaf6c578-510f-f1e1-924f-8cdcd4b723a1

**Comment by averbukh** [comment]
> @averbukh Do we want to see your changes #928 in the release 2020u3?

Yes

**Pull request merged**
