### PR TITLE
Enable MDd flag for windows

### PR DESCRIPTION
**Pull request by Pahandrovich**

### CODE REVIEW

**Comment by Pahandrovich** [comment]
CI 1
http://intel-ci.intel.com/ebbfb227-2545-f158-b561-8cdcd4b723a1

**Comment by Pahandrovich** [comment]
CI 2
http://intel-ci.intel.com/ebc24b12-c52d-f1ff-a8fe-8cdcd4b723a1

**Comment by Pahandrovich** [comment]
CI 3
http://intel-ci.intel.com/ebc27a77-f33c-f13b-a979-8cdcd4b723a1

**Comment by Pahandrovich** [comment]
CI 4
http://intel-ci.intel.com/ebc2e4b2-d2e6-f19f-ae16-8cdcd4b723a1

**Comment by Pahandrovich** [comment]
CI 5
https://intel-ci.intel.com/ebc32eb3-3663-f184-a62f-8cdcd4b723a1

**Review by PetrovKP — APPROVED** [review]

**Pull request merged**
