### PR TITLE
add icx config in makefiles

### PR DESCRIPTION
**Pull request by asrednit**

### CODE REVIEW

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/add_icx_to_examples_cpp

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by napetrov** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by asrednit** [comment]
restart

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by homksei** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by asrednit** [comment]
restart

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Comment by asrednit** [comment]
/intelci: run
set infra_branch=dev/asrednit/enable_xmain

**Review by napetrov — APPROVED** [review]

**Pull request merged**
