### PR TITLE
NuSVM Fixes

### PR DESCRIPTION
**Pull request by owerbat**

### CODE REVIEW

**Review by PetrovKP — APPROVED** [review]

**Comment by owerbat** [comment]
CI: http://intel-ci.intel.com/ebbfcb41-6498-f1ca-90fb-8cdcd4b723a1

**Comment by SmirnovEgorRu** [comment]
https://ecmd.inn.intel.com/commander/link/jobDetails/jobs/ebbfe4a2-e1af-f105-a796-8cdcd4b723a1

**Comment by SmirnovEgorRu** [comment]
http://intel-ci.intel.com/ebbfe4a2-e1af-f105-a796-8cdcd4b723a1

**Pull request merged**
