### PR TITLE
updating links to repo and gh-pages

### PR DESCRIPTION
**Pull request by napetrov**
updating links to repo and gh-pages after migration to new org

### CODE REVIEW

**Comment by outoftardis** [comment]
No changes to the license shield required?

**Comment by napetrov** [comment]
> 
> 
> No changes to the license shield required?

thanks. Also updated across couple other places

**Comment by napetrov** [comment]
make test

**Comment by outoftardis** [comment]
Look at the last few lines of the file below, link to gh-pages also goes through redirect. I think 
 https://raw.githubusercontent.com/napetrov/daal/dev/napetrov-badge/FAQ.md

**Comment by napetrov** [comment]
Yes, but i really don't want to touch FAQ file now. it have lot of not relevant content and i think that we should go ahead and remove it.  Is this ok for you?

**Comment by outoftardis** [comment]
The instructions for cloning the repo require an update:
https://github.com/napetrov/daal/blob/dev/napetrov-badge/docs/README.md

**Comment by outoftardis** [comment]
> Yes, but i really don't want to touch FAQ file now. it have lot of not relevant content and i think that we should go ahead and remove it. Is this ok for you?

Not sure about removing it, but not updating is OK with me

**Pull request merged**
