### PR TITLE
infra: update binary version

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description

### CODE REVIEW

**Comment by napetrov** [comment]
Should be updated in cpp/daal/src/services/dll.rc

**Comment by Alexsandruss** [comment]
https://github.com/intel/scikit-learn-intelex/pull/1414 should fix sklearnex Pre-Commit failures.

**Comment by ethanglaser** [comment]
> [intel/scikit-learn-intelex#1414](https://github.com/intel/scikit-learn-intelex/pull/1414) should fix sklearnex Pre-Commit failures.

Thanks, launched job with all 3 branches: http://intel-ci.com/ee41c917-a057-f1c1-9453-a4bf010d0e2e

**Review by KulikovNikita — APPROVED** [review]

**Review by napetrov — APPROVED** [review]

**Pull request merged**
