### PR TITLE
update version to 2024.4.0

### PR DESCRIPTION
**Pull request by mvtiurin**

### CODE REVIEW

**Review by homksei — APPROVED** [review]

**Review by napetrov — CHANGES_REQUESTED** [review]
let's hold this for a bit

**Comment by avolkov-intel** [comment]
@napetrov can we merge it now, so that I can use newly added result_options from sklearnex side?

**Review by ethanglaser — APPROVED** [review]

**Review by samir-nasibli — APPROVED** [review]

**Review by napetrov — APPROVED** [review]
@maria-Petrova  to finally decide

**Review by maria-Petrova — APPROVED** [review]

**Pull request merged**
