### PR TITLE
Update to 2025.0.0 version

### PR DESCRIPTION
**Pull request by icfaust**
# Description
Upgrade oneDAL to build as 2025.0

Changes proposed in this pull request:
- update makefile.ver
- update bazel configuration
- update documentation
- update deployment package tpl file

### CODE REVIEW

**Review by samir-nasibli — APPROVED** [review]

**Review by mvtiurin — APPROVED** [review]

**Comment by icfaust** [comment]
This PR is now dependent on first merging intel/scikit-learn-intelex#2026

**Review by maria-Petrova — APPROVED** [review]

**Pull request merged**
