### PR TITLE
chore: add OpenSSF Scorecard GitHub Action

### PR DESCRIPTION
**Pull request by homksei**
## Summary

This Pull Request adds a new GitHub Actions workflow that runs the OpenSSF Scorecard tool on our repository.

## Changes

- Added a new workflow file `openssf-scorecard.yml` in the `.github/workflows` directory.

## Motivation

The OpenSSF Scorecard is an automated security tool that performs a series of checks on our codebase and provides a score based on the results. By adding this workflow, we can automate the process of running the Scorecard tool and publishing the results.

The workflow is triggered on the following events:
- On a schedule, every Friday at 21:00 UTC.
- When a push is made to the `main` branch.

### CODE REVIEW

**Review by Alexsandruss — APPROVED** [review]

**Review by Alexsandruss — CHANGES_REQUESTED** [review]
PR has a significant change: badge in README was removed.
Also, PR lacks description.

**Comment by homksei** [comment]
> PR has a significant change: badge in README was removed. Also, PR lacks description.
- Description has been added. 
- Regarding the badge(s). I have removed OpenSSF Scorecard badge from the `README.md` because the usefulness of having these badges is highly questionable. Please let me know if you believe it/they should be re-added or placed elsewhere. By the way, we have also received the OpenSSF Best Practices badge. It might be beneficial to add this instead of the Scorecard badge. What are your thoughts on this? 
@Alexsandruss @ethanglaser @napetrov @syakov-intel 

And here are both badges, just in case: [OpenSSF Best Practices](https://www.bestpractices.dev/projects/8859) [OpenSSF Scorecard](https://securityscorecards.dev/viewer/?uri=github.com/oneapi-src/oneDAL)

**Comment by Alexsandruss** [comment]
@homksei, I think OpenSSF Best Practices badge is perfect for README and should be added.

**Review by napetrov — APPROVED** [review]

**Comment by napetrov** [comment]
@homksei  @ethanglaser  BLAS CIs failures looks a bit strange - ant thoughts?

**Comment by Alexsandruss** [comment]
> @homksei @ethanglaser BLAS CIs failures looks a bit strange - ant thoughts?

It's separate issue out of this PR: https://github.com/oneapi-src/oneDAL/issues/2758

**Pull request merged**
