### PR TITLE
Clean up v1/v2 interfaces

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description
TODOs:
- Remove anything designated "Should be remove in oneDAL 2022.1."
- ensure reset functionality is same (see TODO)

### CODE REVIEW

**Comment by napetrov** [comment]
@ethanglaser  - looks like interface1 not deleted here yet. there are no changes related to daal sources here

**Comment by ethanglaser** [comment]
Splitting into smaller PRs:
oneapi (v1/v2 removal): https://github.com/oneapi-src/oneDAL/pull/2507/files

**Comment by ethanglaser** [comment]
Replaced by https://github.com/oneapi-src/oneDAL/pull/2514

**Pull request closed without merging**
