### PR TITLE
Revert "Implement DPC++ sparse gemm and gemv primitives  (#2668)"

### PR DESCRIPTION
**Pull request by Vika-F**
Reverting the PR that causes sporadic failures in test_gemm_dpc and test_gemv_dpc in private CI.

### CODE REVIEW

**Comment by Vika-F** [comment]
http://intel-ci.intel.com/ef022c30-4eed-f160-aa82-a4bf010d0e2e

**Comment by Alexandr-Solovev** [comment]
may be it makes sense to remove just tests from CI? due to as I understand we don't use this functionality in intelex yet, and, probably, it will be easier to investigate issues and merge fix instead of reverting the full big pr

**Comment by Vika-F** [comment]
@Alexandr-Solovev 
PR #2745 was created to remove failing tests from the CI.

**Pull request closed without merging**
