### PR TITLE
Brute-Force kNN Constructor's Fix

### PR DESCRIPTION
**Pull request by owerbat**
Fix of the constructor which affected cloning of the algorithm

### CODE REVIEW

**Comment by owerbat** [comment]
/intelci: run
set infra_branch=dev/ntimakin-bf_knn_tests_master

**Comment by owerbat** [comment]
/intelci: restart
set infra_branch=dev/ntimakin-bf_knn_tests_master

**Comment by owerbat** [comment]
/intelci: run
set infra_branch=dev/ntimakin-bf_knn_tests_master

**Review by Alexsandruss — APPROVED** [review]

**Review by PetrovKP — APPROVED** [review]

**Pull request merged**
