### PR TITLE
fix wrong type in CSVDataSource

### LINKED ISSUE #1670: precision loss in csvDataSource while compile with DAAL_DATA_TYPE=double
**Describe the bug**
When use `FileDataSource<CSVFeatureManager>` to read data from csv file, the numeric is always be parsed as `float` instead `DAAL_DATA_TYPE`.

***First Case***
csv  parse func call `readNumeric` here

https://github.com/oneapi-src/oneDAL/blob/5269acce582cdb680df65567548cd9575e2ac35b/cpp/daal/include/data_management/data_source/csv_feature_manager.h#L71-L76

`readNumeric` defined here, always return float.

https://github.com/oneapi-src/oneDAL/blob/5269acce582cdb680df65567548cd9575e2ac35b/cpp/daal/include/data_management/data_source/csv_feature_manager.h#L102-L106

***Second Case***
A double specialization call `services::daal_string_to_float` instead of `services::daal_string_to_double`
https://github.com/oneapi-src/oneDAL/blob/5269acce582cdb680df65567548cd9575e2ac35b/cpp/daal/include/data_management/data_source/modifiers/csv/modifier.h#L146-L150

**To Reproduce**
1. Code
```C++
#include <iostream>
#include <iomanip>
#include <limits>
#include "daal.h"

using namespace daal::data_management;

const std::string csvFileName = "data.csv";
const CsvDataSourceOptions csvOptions = CsvDataSourceOptions::allocateNumericTable | CsvDataSourceOptions::createDictionaryFromContext;

void printNumericTable(NumericTable * dataTable, const char * message = "");
class MyMaxFeatureModifier;
void readDefault();
void readCustom();


int main(int argc, char * argv[])
{
    readDefault();
    readCustom();
    return 0;
}

void readDefault()
{
    FileDataSource<CSVFeatureManager> ds(csvFileName, csvOptions);
    ds.loadDataBlock();
    printNumericTable(ds.getNumericTable().get(), "readDefault function result:");
}

void readCustom()
{
    FileDataSource<CSVFeatureManager> ds(csvFileName, csvOptions);
    ds.getFeatureManager().addModifier(
        features::list(0, 1),
        modifiers::csv::custom<MyMaxFeatureModifier>());
    ds.loadDataBlock();
    printNumericTable(ds.getNumericTable().get(), "MyMaxFeatureModifier function result:");
}


class MyMaxFeatureModifier : public modifiers::csv::FeatureModifier
{
public:
    virtual void initialize(modifiers::csv::Config & config)
    {
        config.setNumberOfOutputFeatures(1);
    }

    virtual void apply(modifiers::csv::Context & context)
    {
        auto a = context.getTokenAs<DAAL_DATA_TYPE>(0);
        auto b = context.getTokenAs<DAAL_DATA_TYPE>(1);
        context.getOutputBuffer()[0] = a > b ? a : b;
    }
};

void printNumericTable(NumericTable * dataTable, const char * message)
{

    size_t nRows                            = dataTable->getNumberOfRows();
    size_t nCols                            = dataTable->getNumberOfColumns();

    std::cout << "total rows:" << nRows << std::endl;
    BlockDescriptor<DAAL_DATA_TYPE> block;
    dataTable->getBlockOfRows(0, nRows, readOnly, block);
    auto array = block.getBlockPtr();
    auto precision = std::numeric_limits<DAAL_DATA_TYPE>::max_digits10;

    std::cout << std::setiosflags(std::ios::left);
    std::cout << message << std::endl;

    for (size_t i = 0; i < nRows; i++)
    {
        for (size_t j = 0; j < nCols; j++)
        {
            std::cout << std::setw(precision+5) << std::setprecision(precision);
            std::cout << array[i * nCols + j];
        }
        std::cout << std::endl;
    }
    std::cout << std::endl;
    dataTable->releaseBlockOfRows(block);
}

```
2. Data.csv
```CSV
0.0, 0.01234567890123456789
0.01, 0.0123456789012345678
0.012, 0.012345678901234567
0.0123, 0.01234567890123456
0.01234, 0.0123456789012345
0.012345, 0.012345678901234
0.0123456, 0.01234567890123
0.01234567, 0.0123456789012
0.012345678, 0.012345678901
0.0123456789, 0.01234567890
0.01234567890, 0.0123456789
0.012345678901, 0.012345678
0.0123456789012, 0.01234567
0.01234567890123, 0.0123456
0.012345678901234, 0.012345
0.0123456789012345, 0.01234
0.01234567890123456, 0.0123
0.012345678901234567, 0.012
0.0123456789012345678, 0.01
0.01234567890123456789, 0.0

```
3. Makefile
```Makefile
build: poc_float poc_double

poc_float: test_csv_precision.cc
	dpcpp -qdaal -DDAAL_DATA_TYPE=float -o $@ $^

poc_double: test_csv_precision.cc
	dpcpp -qdaal -DDAAL_DATA_TYPE=double -o $@ $^


run-float: poc_float
	./poc_float

run-double: poc_double
	./poc_double

clean:
	rm poc_float poc_double
```
4. `make run-double`

**Expected behavior**
parse as `double` when `DAAL_DATA_TYPE` is `double`.

**Output/Screenshots**

***Current output with precision loss.***

2021-06-02-213256_1195x1619_scrot

***Expected output without precision loss.***
2021-06-02-214055_1910x1698_scrot

**Environment:**
 - OS: ArchLinux
 - Compiler: Intel(R) oneAPI DPC++ Compiler 2021.2.0 (2021.2.0.20210317)
 - Version: 2021.2.0

### PR DESCRIPTION
**Pull request by cmsxbc**
# Description
Fixes #1670 

Changes proposed in this pull request:
- Wrong type in `daal::data_management::ModifierIface`
- Wrong type in `daal::data_management::modifiers::csv::Context`

### CODE REVIEW

**Comment by PetrovKP** [comment]
@Mergifyio rebase

**Comment by PetrovKP** [comment]
build: http://intel-ci.intel.com/ebc9336a-4a95-f1b0-a1b5-8cdcd4b723a1

**Review by SmirnovEgorRu — APPROVED** [review]

**Comment by SmirnovEgorRu** [comment]
@cmsxbc, thank you for the contribution!

**Pull request merged**
