### PR TITLE
t-SNE summarization kernel parallelization

### PR DESCRIPTION
**Pull request by Pahandrovich**

### CODE REVIEW

**Comment by Pahandrovich** [comment]
http://intelci.intel.com/eca2fe8d-246c-f116-8807-8cdcd4b723a1

**Comment by Pahandrovich** [comment]
http://intel-ci.intel.com/eca4a4c8-aff7-f1d6-a2c9-8cdcd4b723a1

**Comment by narendrachaudhary51** [comment]
@Pahandrovich The parallelization of the summarization kernel will not be beneficial without Qtree building. It might be same or slower then single threaded. This is due to irregular memory access. However, with the new tree building memory accesses become regular.

**Review by KalyanovD — APPROVED** [review]
Please, resolve questions regarding "auto" usage.

**Pull request closed without merging**
