### PR TITLE
Fixes for the invalid pointer alignment 

### PR DESCRIPTION
**Pull request by KulikovNikita**

### CODE REVIEW

**Comment by KulikovNikita** [comment]
[http://intel-ci.intel.com/](http://intel-ci.intel.com/ed7fbd58-636a-f137-8731-a4bf010d0e2e)

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ed7fdd63-a9b6-f1c7-9890-a4bf010d0e2e

**Review by Alexsandruss — CHANGES_REQUESTED** [review]
Rebase on master branch to check with updated dpc++ compiler 2023.0 in CI

**Comment by KulikovNikita** [comment]
> Rebase on master branch to check with updated dpc++ compiler 2023.0 in CI

Done. Anyway it is working only partially for now)

**Comment by KulikovNikita** [comment]
[http://intel-ci.intel.com/](http://intel-ci.intel.com/ed81e7cc-57fc-f163-8706-a4bf010d0e2e)

**Comment by KulikovNikita** [comment]
Experiment: http://intel-ci.intel.com/ed81ead7-5f70-f1ed-a544-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
Another experiment: http://intel-ci.intel.com/ed81ebae-19fe-f176-9890-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
Some of changes were borrowed in #2225

**Pull request closed without merging**
