### PR TITLE
Introducing dispatching only on Linux/MacOS

### PR DESCRIPTION
**Pull request by KulikovNikita**

### CODE REVIEW

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee474489-3983-f1d0-81cf-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee474fe3-a4f0-f1ce-9047-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee475142-0328-f108-a9d7-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee47cc72-2965-f1c0-8884-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee47d4f6-5099-f181-b558-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee47eada-5e0c-f172-ba73-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee4800b6-535b-f114-85a0-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee481c24-d495-f1fe-9453-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee484059-a2c4-f15a-84a9-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee4892dc-26a7-f1d5-ba73-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee489b49-7689-f1d7-a4f0-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee48a726-1592-f119-becf-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee48aad8-551a-f148-86a6-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
Another manually started CI job: http://intel-ci.intel.com/ee48b22c-068f-f13c-ba73-a4bf010d0e2e

**Comment by samir-nasibli** [comment]
@KulikovNikita please rebase your branch and run CI again

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee48c187-dbc8-f1f2-863c-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
Updated sklearnex: http://intel-ci.intel.com/ee48c807-5f50-f11e-9fc7-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee48dc16-8f02-f156-84a9-a4bf010d0e2e

**Review by ethanglaser — APPROVED** [review]
Internal CI looks good, will wait for external CI after merging corresponding sklearnex PR

**Pull request merged**
