### PR TITLE
[DOC] New structure

### PR DESCRIPTION
**Pull request by outoftardis**
# Description

- New chapters for oneAPI and DAAL interfaces.
- DAAL interfaces: 
  - moved old content there
  - added notes to the algorithms with oneAPI interfaces with links to new descriptions
  - removed sycl tables content as discussed
- oneAPI interfaces: c
  - added content from spec + autogenerated from doxygen
  - added links to examples for all algorithms
  - minor changes in "build applications" chapter based on peer review
- Updated Get Started topics
- Fixed css for doxygen descriptions
- Removed Beta from title

### CODE REVIEW

**Comment by outoftardis** [comment]
output: https://outoftardis.github.io/daal/ (svm and decision forest chapters are not in there but there are placeholder for them)

**Review by michael-smirnov — APPROVED** [review]
No comments about data management part in oneAPI interfaces

**Comment by rlnx** [comment]
Discussed with @outoftardis in IM, there are still some items need to be fixed.

**Review by rlnx — APPROVED** [review]

**Pull request merged**
