### PR TITLE
[2020-mnt] BF kNN example fix for win platform

### PR DESCRIPTION
**Pull request by Alexsandruss**
# Description
Add brute force k-Nearest Neighbors example for win platform

### CODE REVIEW

**Comment by Alexsandruss** [comment]
http://intel-ci.intel.com/eaf74dd4-728a-f16f-acac-8cdcd4b723a1

**Comment by PetrovKP** [comment]
http://intel-ci.intel.com/eaf78410-58cc-f12f-a2df-8cdcd4b723a1?

**Comment by PetrovKP** [comment]
http://intel-ci.intel.com/eaf79da3-43b1-f1b2-bc30-8cdcd4b723a1?

**Comment by PetrovKP** [comment]
http://intel-ci.intel.com/eaf81a0e-23b2-f14c-ac8d-8cdcd4b723a1?

**Comment by PetrovKP** [comment]
http://intel-ci.intel.com/eaf84041-4ea6-f14c-920b-8cdcd4b723a1?

**Review by SmirnovEgorRu — APPROVED** [review]

**Pull request merged**
