### PR TITLE
CI: fix docker nightly

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by ethanglaser** [comment]
@keeranroth this is a follow-up to https://github.com/oneapi-src/oneDAL/pull/2700 related to docker validation, is there any objection to also adding the conda activate inside the conda init conditional?

**Comment by keeranroth** [comment]
@ethanglaser There is no objection from my side. If I want to be in a conda environment when running this locally, I can load it before running, so there isn't any real change to the workflow. The changes look good to me

**Review by napetrov — APPROVED** [review]

**Pull request merged**
