### PR TITLE
Initial commit with introduced graph functionality

### PR DESCRIPTION
**Pull request by bysheva**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
initial graph functionality

### CODE REVIEW

**Comment by bysheva** [comment]
/intelci: run
set infra_repo=dev/napetrov_graph_infra

**Comment by napetrov** [comment]
/intelci: restart
set infra_branch=dev/napetrov_graph_infra

**Comment by napetrov** [comment]
/intelci: restart
set infra_branch=master

**Pull request closed without merging**
