### PR TITLE
fix inconsistency in brownboost and svm

### PR DESCRIPTION
**Pull request by PivovarA**

### CODE REVIEW

**Comment by PivovarA** [comment]
make test

**Comment by ShvetsKS** [comment]
make test

**Comment by ShvetsKS** [comment]
Could you clarify why `Batch` class in `kdtree_knn_classification_training_batch.h` was not extended by similar constructor?

**Comment by PivovarA** [comment]
make test

**Comment by PivovarA** [comment]
make test

**Comment by PivovarA** [comment]
> Could you clarify why `Batch` class in `kdtree_knn_classification_training_batch.h` was not extended by similar constructor?

In general, I can add such a constructor, but kdtree-knn counts the number of classes within itself. Therefore, adding this constructor will not change anything.
Adding nClasses parameter specifically to kdtree-knnis is a bit more difficult process and will require more detailed consideration.

**Pull request merged**
