### PR TITLE
replace of label with response for svm, kmeans, knn, df

### PR DESCRIPTION
**Pull request by makart19**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by makart19** [comment]
/intelci: run
set daal4py_branch=dev/amk_response
set daal4py_repo=https://github.com/makart19/daal4py.git

**Review by amgrigoriev — APPROVED** [review]

**Review by vlad-nazarov — APPROVED** [review]

**Review by averbukh — APPROVED** [review]

**Review by KulikovNikita — APPROVED** [review]

**Pull request merged**
