### PR TITLE
LR Fixes

### PR DESCRIPTION
**Pull request by KulikovNikita**

### CODE REVIEW

**Comment by Pahandrovich** [comment]
gnu
http://intel-ci.com/ec3b1041-677f-f141-9ca7-8cdcd4b723a1

**Comment by Pahandrovich** [comment]
MSVS
http://intel-ci.intel.com/ec3b10be-9d7b-f16f-8a3d-8cdcd4b723a1

**Comment by Pahandrovich** [comment]
rerun gnu
http://intel-ci.intel.com/ec3b18e0-d546-f11e-bc6f-8cdcd4b723a1

**Comment by KulikovNikita** [comment]
New gnu eval: http://intel-ci.intel.com/ec3b1a5c-26ae-f1de-9144-8cdcd4b723a1
new msv eval: http://intel-ci.intel.com/ec3b1a9d-60d4-f1e6-823b-8cdcd4b723a1

**Comment by KulikovNikita** [comment]
New gnu eval: http://intel-ci.intel.com/ec3b3021-6ea1-f11a-9057-8cdcd4b723a1
New msv eval: http://intel-ci.intel.com/ec3b304d-4159-f19e-abbf-8cdcd4b723a1

**Review by napetrov — APPROVED** [review]
Assuming internal CI is passing

**Review by Pahandrovich — APPROVED** [review]

**Pull request merged**
