### PR TITLE
Doc update: converted algorithms & added placeholders

### PR DESCRIPTION
**Pull request by outoftardis**
# Description

[output](https://outoftardis.github.io/daal/)

- Converted:
  - training alternative (model builders) for all affected algorithms: ([linear regression](https://outoftardis.github.io/daal/dev_guide/algorithms/linear_ridge_regression/linear-regression.html#linear-regression), [svm](https://outoftardis.github.io/daal/dev_guide/algorithms/svm/support-vector-machine-classifier.html#usage-of-training-alternative), [svm-multi](https://outoftardis.github.io/daal/dev_guide/algorithms/svm_multi_class/multi-class-classifier.html#usage-of-training-alternative), [logistic regression](https://outoftardis.github.io/daal/dev_guide/algorithms/logistic_regression/logistic-regression.html#usage-of-training-alternative), [gbt regression](https://outoftardis.github.io/daal/dev_guide/algorithms/gradient_boosted_trees/gradient-boosted-trees-regression.html#usage-of-training-alternative), [gbt classification](https://outoftardis.github.io/daal/dev_guide/algorithms/gradient_boosted_trees/gradient-boosted-trees-classification.html#usage-of-training-alternative), [decision forest classification](https://outoftardis.github.io/daal/dev_guide/algorithms/decision_forest/decision-forest-classification.html#usage-of-training-alternative))
  - [online & distributed processes for linear and ridge regression](https://outoftardis.github.io/daal/dev_guide/algorithms/linear_ridge_regression/linear-ridge-regression-computation.html)
  - [classification stump](https://outoftardis.github.io/daal/dev_guide/algorithms/stump/classification.html) & [regression stump](https://outoftardis.github.io/daal/dev_guide/algorithms/stump/regression.html)
  - descriptions of usage models for [classification ](https://outoftardis.github.io/daal/dev_guide/usage/training-and-prediction/classification.html)and [regression](https://outoftardis.github.io/daal/dev_guide/usage/training-and-prediction/regression.html)
- Added placeholders for all not yet converted algorithms (empty or partly converted topic with a link to the old docs)
- Updated links to examples

### CODE REVIEW

**Comment by outoftardis** [comment]
Is "GPU Examples" a correct naming for [these](https://github.com/oneapi-src/oneDAL/tree/master/examples/cpp_sycl)?
I added links to these examples from algorithms that have GPU support (previously they were just a part of the doc, with no links to them). Output is also updated.

**Comment by napetrov** [comment]
> 
> 
> Is "GPU Examples" a correct naming for [these](https://github.com/oneapi-src/oneDAL/tree/master/examples/cpp_sycl)?
> I added links to these examples from algorithms that have GPU support (previously they were just a part of the doc, with no links to them). Output is also updated.

I would mention this as DPC++ examples - they will run on CPU as well. 
@rlnx - guess we also should rename cpp_sycl to just dpcpp at some stage?

**Comment by outoftardis** [comment]
Renamed to DPC++.
In algorithms I've added DPC++ as a separate tab, e.g. see [linear regression](https://outoftardis.github.io/daal/dev_guide/algorithms/linear_ridge_regression/linear-ridge-regression-computation.html#examples)

**Pull request merged**
