### PR TITLE
Update mkl fpk GPU and compiler version for 2024.2.0

### PR DESCRIPTION
**Pull request by mvtiurin**
Cherry pick commits from main.

### CODE REVIEW

**Comment by Vika-F** [comment]
It seems this is a duplicate of https://github.com/oneapi-src/oneDAL/pull/2699
And #2699 is already merged.

**Comment by mvtiurin** [comment]
@Vika-F it's the same update as in #2699 but for **rls/2024.2.0-rls** branch.

**Review by Vika-F — APPROVED** [review]
The changes look good to me.
The failures in pre-commit testing look unrelated to those changes.

**Comment by Vika-F** [comment]
> @Vika-F it's the same update as in #2699 but for **rls/2024.2.0-rls** branch.

Sorry, hadn't noticed that.

**Pull request merged**
