### PR TITLE
FIX: kmeans_init bazel test enabling

### PR DESCRIPTION
**Pull request by ethanglaser**
- Update kmeans_init BUILD file so tests are ran from CI bazel test scope (in current main branch tests are NOT ran)
- Fix infinite loop kmeans_init++ that led to timeout in testing

### CODE REVIEW

**Review by Alexandr-Solovev — APPROVED** [review]
In general LGTM, but please clarify the dbi metric via onedal-benchmarks

**Comment by ethanglaser** [comment]
> In general LGTM, but please clarify the dbi metric via onedal-benchmarks

This should have no impact on performance

**Pull request merged**
