### PR TITLE
fix: CPATH variable fix

### PR DESCRIPTION
**Pull request by Alexandr-Solovev**
# Description
The pr fixes the value of CPATH environment variable. In both oneDAL layout it must be /include, not /include/dal

### CODE REVIEW

**Comment by napetrov** [comment]
@maria-Petrova  - if we would like to integrate it - probably worth validation via self-service prior to drop

**Comment by ethanglaser** [comment]
What's reason for change? Please add description

**Review by ethanglaser — APPROVED** [review]

**Pull request merged**
