### PR TITLE
Performance optimization for SVM predict

### PR DESCRIPTION
**Pull request by PetrovKP**
1. Improve blocking for SVM predict by splitting support vectors
2. Extend LS storage memory struct for TLS case

Problem | Before, ms | After, ms | Speedup
--| -- | -- | --
ijcnn | 940 | 110 | **8.2**
klaverjas | 7400 | 2030 | **2.6**
connect4  | 1050 | 340 | **3.2**
mnist | 3120 | 1680 | **1.9**
sensit | 1400 | 400 | **3.5**
skin_segmentation | 2540 | 920 | **2.8**
covertype| 32400 | 11700 | **2.8**

### CODE REVIEW

**Comment by PetrovKP** [comment]
perf: http://intel-ci.intel.comeb2c614c-2bf1-f135-8959-8cdcd4b723a1
daal4py: http://intel-ci.intel.comeb2c6150-0e5b-f1c6-8f9b-8cdcd4b723a1

**Comment by PetrovKP** [comment]
daal4py: http://intel-ci.intel.com/eb2cd223-96ed-f11e-9d5e-8cdcd4b723a1?
perf: http://intel-ci.intel.com/eb2cd222-52ad-f196-9d85-8cdcd4b723a1

**Comment by masdevas** [comment]
LGTM

**Review by masdevas — APPROVED** [review]

**Pull request merged**
