### PR TITLE
Changes required for daal4py USM integration

### PR DESCRIPTION
**Pull request by michael-smirnov**
This is needed for https://github.com/IntelPython/daal4py/pull/550
CI oneDAL+daal4py: http://intel-ci.intel.com/eb7cbb3a-9ba7-f109-b73e-8cdcd4b723a1

### CODE REVIEW

**Comment by PetrovKP** [comment]
@michael-smirnov  can do you attach a result private CI with you changes?

**Review by rlnx — APPROVED** [review]

**Review by KulikovNikita — APPROVED** [review]

**Comment by michael-smirnov** [comment]
@Mergifyio backport rls/2021.2-rls

**Pull request merged**
