### PR TITLE
split table event modifications

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description
Fix for split_table bazel test failures in oneDAL internal CI

### CODE REVIEW

**Comment by ethanglaser** [comment]
This job should have actual resolution of bazel test error - https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/edf5a751-6c51-f14a-98ad-a4bf010d0e2e

**Comment by ethanglaser** [comment]
image
image
Before: 
image
After:
image

**Comment by ethanglaser** [comment]
See this log for successful test split table result: [job](https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/edf5a751-6c51-f14a-98ad-a4bf010d0e2e), [log](https://ecmd.jf.intel.com/commander/link/workspaceFile/workspaces/JF-DAL?jobStepId=edf5a9ec-c22c-f1f6-af5a-a4bf010d0e2e&fileName=dev.edf5a9ec-c22c-f1f6-af5a-a4bf010d0e2e.log&jobName=DAAL_eval_icc2021_src_dev_eglaser_bazel_res_38ed6a7_ethan.glaser%40intel.com_%28May-18_18_12_UTC_Id_edf5a751-6c51-f14a-98ad-a4bf010d0e2e%29&jobId=edf5a751-6c51-f14a-98ad-a4bf010d0e2e&diagCharEncoding=&resourceName=sdpdal123374&completed=1)

**Review by KulikovNikita — APPROVED** [review]

**Pull request merged**
