### PR TITLE
fix(cmake,win32,vs2022): add missing SYCL flags to linking step

### PR DESCRIPTION
**Pull request by ahuber21**
Building the `daal/cpp_sycl` examples with Visual Studio 2022 and using CMake>=3.24 results in a broken linking step because the required SYCL flags are not included in the command.
The change adds the missing flags for the `daal/cpp_sycl` examples.

### CODE REVIEW

**Review by KulikovNikita — APPROVED** [review]

**Review by Alexsandruss — APPROVED** [review]

**Review by samir-nasibli — APPROVED** [review]

**Review by napetrov — APPROVED** [review]
Looks good. Assuming CI would pass

**Pull request merged**
