### PR TITLE
Subgraph isomorphism: error handling when target graph is smaller than pattern

### PR DESCRIPTION
**Pull request by orazve**
Check + test

### CODE REVIEW

**Review by orrrrtem — APPROVED** [review]

**Comment by orrrrtem** [comment]
Probably, one more test should be added: sizes are equal.

**Comment by orazve** [comment]
> Probably, one more test should be added: sizes are equal.

Equal sizes of graphs are correct case. It is not a bad argument.

**Comment by orazve** [comment]
http://intel-ci.intel.com/ebdf3270-cc55-f105-a2f7-8cdcd4b723a1

**Pull request closed without merging**
