### PR TITLE
2021.2.2 -> 20221.2.3

### PR DESCRIPTION
**Pull request by PetrovKP**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by PetrovKP** [comment]
/intelci: restart
set daal4py_branch=rls/2021.2.3-rls
set infra_branch=dev/2021.2.3-update

**Comment by PetrovKP** [comment]
ebb63b11-9c3e-f174-b6f8-8cdcd4b723a1

**Comment by PetrovKP** [comment]
ebb6f93f-08b8-f11f-9bd8-8cdcd4b723a1

**Review by napetrov — APPROVED** [review]

**Review by SmirnovEgorRu — APPROVED** [review]

**Pull request merged**
