### PR TITLE
[2020-u3-rls] Fix class voting for kNN

### PR DESCRIPTION
**Pull request by Alexsandruss**
# Description
Fix class voting for brute force and kdtree methods of k-Nearest Neighbors

### CODE REVIEW

**Review by averbukh — APPROVED** [review]
There are some minor coding-style related issues that could be addressed later.

**Comment by Alexsandruss** [comment]
http://intel-ci.intel.com/eaf9b447-4401-f1fa-ba68-8cdcd4b723a1

**Comment by Alexsandruss** [comment]
http://intel-ci.intel.com/eaf9bddb-fae7-f1b2-9a95-8cdcd4b723a1

**Review by SmirnovEgorRu — APPROVED** [review]

**Pull request merged**
