### PR TITLE
KMeans spmd timeout fix

### PR DESCRIPTION
**Pull request by inteldimitrius**
# Description
Due to sporadic failures in Kmeans Init in distributed mode, temporary solution is to replace bcast() with allreduce().

### CODE REVIEW

**Review by Alexandr-Solovev — APPROVED** [review]

**Comment by ethanglaser** [comment]
Please merge main into branch

**Comment by ethanglaser** [comment]
CI with https://github.com/intel/scikit-learn-intelex/pull/1691: http://intel-ci.intel.com/eec12213-8bec-f165-904e-a4bf010d0e2e

**Review by ethanglaser — APPROVED** [review]

**Pull request merged**
