### PR TITLE
Decision Forest: fix gaps (#1014)

### PR DESCRIPTION
**Pull request by agorshk**
cherry-pick from https://github.com/oneapi-src/oneDAL/pull/1014

### CODE REVIEW

**Comment by agorshk** [comment]
/intelci: run
set infra_branch=dev/agorshk-forest_fix_gaps_mnt

**Review by PetrovKP — APPROVED** [review]

**Comment by agorshk** [comment]
/intelci: rerun
set infra_branch=dev/agorshk-forest_fix_gaps_mnt

**Comment by agorshk** [comment]
/intelci: restart
set infra_branch=dev/agorshk-forest_fix_gaps_mnt

**Comment by PetrovKP** [comment]
@Mergify rebase

**Comment by PetrovKP** [comment]
/intelci: run
set infra_branch=dev/agorshk-forest_fix_gaps_mnt

**Comment by agorshk** [comment]
/intelci: run
set infra_branch=dev/agorshk-forest_fix_gaps_mnt

**Pull request merged**
