### PR TITLE
Test delete compression functionality

### PR DESCRIPTION
**Pull request by PetrovKP**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by KulikovNikita — APPROVED** [review]

**Comment by PetrovKP** [comment]
not relevant.

**Comment by PetrovKP** [comment]
@Mergifyio rebase

**Comment by napetrov** [comment]
@KulikovNikita @Alexsandruss - this is what we would like to cleanup.

But first this need to be marked as deprecated from 2023.2 release

**Pull request closed without merging**
