### PR TITLE
Remove part of unnecessary transpositions from batch SVD

### PR DESCRIPTION
**Pull request by Vika-F**
There are a lot of unnecessary matrix transpositions and memory allocations in current SVD implementation.
I plan to remove all (or most) of them. This first step removes transpositions from compute_seq function that is used in some cases of batch SVD.

SVD(A) = U * S * V'T, where U and V are orthogonal matrices, S is a diagonal matrix and V'T is a transposed matrix V.
SVD(A'T) = V * S * U'T - this knowledge is used in the changes.

### CODE REVIEW

**Comment by Vika-F** [comment]
/intelci: run
set infra_branch=dev/vsfedoto/pcasvd_fix

**Comment by KalyanovD** [comment]
http://intel-ci.intel.com/ec989333-f5e5-f102-b1a3-8cdcd4b723a1

**Comment by Vika-F** [comment]
/intelci: run
set infra_branch=dev/vsfedoto/pcasvd_fix

**Comment by Vika-F** [comment]
https://intel-ci.intel.com/ec9a1977-5917-f135-b0a6-8cdcd4b723a1

**Comment by Vika-F** [comment]
http://intel-ci.intel.com/ec9b897f-c42a-f1fe-8f55-8cdcd4b723a1

**Comment by Vika-F** [comment]
http://intel-ci.intel.com/ec9b985a-34d9-f179-95c4-8cdcd4b723a1

**Comment by Vika-F** [comment]
/intelci: run
set infra_branch=dev/vsfedoto/pcasvd_fix

**Comment by Vika-F** [comment]
http://intel-ci.intel.com/eca50cfb-32be-f1eb-a56e-8cdcd4b723a1

**Comment by Vika-F** [comment]
/intelci: run
set infra_branch=dev/vsfedoto/pcasvd_fix

**Comment by Vika-F** [comment]
http://intel-ci.intel.com/eca6421c-3488-f1cd-8375-8cdcd4b723a1

**Comment by Vika-F** [comment]
http://intel-ci.intel.com/eca68336-f699-f1b2-a1a0-8cdcd4b723a1

**Comment by Vika-F** [comment]
/intelci: run performance
set get_build=eca4a328-4dbb-f105-b511-8cdcd4b723a1

**Review by Alexsandruss — APPROVED** [review]

**Review by Pahandrovich — APPROVED** [review]

**Pull request merged**
