### PR TITLE
fix: Distributed Pca singular values computation fix

### PR DESCRIPTION
**Pull request by Alexandr-Solovev**
# Description
The pr contains fix for correct singular values computation. We discovered that singular values don't match between batch and spmd. The issue was in computational logic, where singular values compute function takes the local number of rows, instead of global. The fix has been added.

### CODE REVIEW

**Comment by ethanglaser** [comment]
Please clang and rebase

**Review by samir-nasibli — COMMENTED** [review]
Generally looks good to me, but it would be better to have meaningful description (What and when was the issue? and how it fixes it?) for the PR.

**Pull request merged**
