### PR TITLE
fix for lnk with mkl

### PR DESCRIPTION
**Pull request by makart19**

### CODE REVIEW

**Comment by makart19** [comment]
/intelci: run
set infra_branch=dev/amk_lnk_mkl_1027
set WANT_MKL_ATS_VERSION=2021u1/20201027

**Comment by makart19** [comment]
/intelci: run
set infra_branch=dev/amk_lnk_mkl_1027
set WANT_MKL_ATS_VERSION=2021u1/20201027

**Comment by homksei** [comment]
/intelci: run
set infra_branch=dev/amk_lnk_mkl_1023

**Comment by homksei** [comment]
@Mergifyio clone rls/2021-gold-mnt

**Comment by homksei** [comment]
@Mergifyio copy rls/2021-gold-mnt

**Comment by makart19** [comment]
@Mergifyio backport rls/2021-gold-mnt

**Pull request closed without merging**
