### PR TITLE
Safety checks: SyclHomogenNumericTable

### PR DESCRIPTION
**Pull request by michael-smirnov**

### CODE REVIEW

**Review by KulikovNikita — APPROVED** [review]

**Review by averbukh — APPROVED** [review]

**Comment by michael-smirnov** [comment]
CI: https://intel-ci.intel.com/eb0fcd3f-63f6-f17e-a6d9-8cdcd4b723a1

**Comment by michael-smirnov** [comment]
CI: http://intel-ci.intel.com/eb11db83-945a-f1fa-b6a8-8cdcd4b723a1

**Comment by michael-smirnov** [comment]
CI: http://intel-ci.intel.com/eb12a247-e0aa-f1e6-84ce-8cdcd4b723a1

**Comment by michael-smirnov** [comment]
benchmarks: http://intel-ci.intel.com/eb12d4c1-16dd-f1a9-bde5-8cdcd4b723a1

**Comment by michael-smirnov** [comment]
CI: http://intel-ci.intel.com/eb136db1-8d1b-f1d4-a974-8cdcd4b723a1

**Pull request merged**
