### PR TITLE
Disable FP64 emulation in bazel tests

### PR DESCRIPTION
**Pull request by napetrov**
# Description
Disable FP64 emulation variables set in case of bazel tests

### CODE REVIEW

**Comment by Alexsandruss** [comment]
@napetrov, will you add any additional changes to this PR?

**Comment by napetrov** [comment]
> @napetrov, will you add any additional changes to this PR?

yes, moving to draft for now

**Review by Alexandr-Solovev — CHANGES_REQUESTED** [review]
We have error in bazel tests:
terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  Required aspect fp64 is not supported on the device

**Comment by napetrov** [comment]
> We have error in bazel tests: terminate called after throwing an instance of 'sycl::_V1::exception' what(): Required aspect fp64 is not supported on the device

this means that tests have to be updated so they can run on systems without FP64 support

**Pull request closed without merging**
