### PR TITLE
AVX/SSSE3/AVX512_MIC ISA cleanup

### PR DESCRIPTION
**Pull request by napetrov**
# Description
Cleaning remain of dropped instruction sets

### CODE REVIEW

**Comment by ethanglaser** [comment]
https://github.com/search?q=repo%3Anapetrov%2Fdaal+avx512_mic&type=code
If want to remove all mentions of avx512_mic

**Comment by napetrov** [comment]
> https://github.com/search?q=repo%3Anapetrov%2Fdaal+avx512_mic&type=code If want to remove all mentions of avx512_mic

Not sure that i get point here. All those entries are removed and this search line runs against master branch while removal happened in feature branch.

**Comment by ethanglaser** [comment]
Would we want to remove/substitute avx with avx512 in bottom of INSTALL.md - https://github.com/oneapi-src/oneDAL/blob/master/INSTALL.md?

**Comment by ethanglaser** [comment]
A few last observations - mentions of plain avx currently (your discretion is better than mine here):
https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/externals/service_blas_mkl.h#L41-L42
https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/externals/service_lapack_mkl.h#L41-L42
https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/externals/service_spblas_mkl.h#L41-L42
https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/services/compiler/generic/env_detect_features.cpp#L102-L120 - couple mentions here but its in a avx512 function so not sure if they should be cleaned
https://github.com/oneapi-src/oneDAL/blob/master/dev/bazel/config/cpudetect.cpp#L86-L120 - similar to above
https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/threading/export_mac.def#L62-L83
https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/threading/export_mac.def#L154-L185
https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/threading/export_mac.def#L205-L210
https://github.com/oneapi-src/oneDAL/blob/master/cpp/oneapi/dal/backend/primitives/intersection/intersection.hpp#L365

**Comment by napetrov** [comment]
> A few last observations - mentions of plain avx currently (your discretion is better than mine here): https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/externals/service_blas_mkl.h#L41-L42 https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/externals/service_lapack_mkl.h#L41-L42 https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/externals/service_spblas_mkl.h#L41-L42 https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/services/compiler/generic/env_detect_features.cpp#L102-L120 - couple mentions here but its in a avx512 function so not sure if they should be cleaned https://github.com/oneapi-src/oneDAL/blob/master/dev/bazel/config/cpudetect.cpp#L86-L120 - similar to above https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/threading/export_mac.def#L62-L83 https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/threading/export_mac.def#L154-L185 https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/threading/export_mac.def#L205-L210 https://github.com/oneapi-src/oneDAL/blob/master/cpp/oneapi/dal/backend/primitives/intersection/intersection.hpp#L365

Thanks!
first 3 on service functions - we will be using MKL AVX kernels on mac. This is lowest that supported there.  And export_mac.def are exporting avx functions from FPK.

on CPU detects - those are again for MacOS avx identification and make no harm for us

the only questionable is last on intersect which is graph experimental functionality - changed it to AVX2 and think it would be working there as well.

**Review by ethanglaser — APPROVED** [review]

**Pull request merged**
