### PR TITLE
[DOC] Separated API from Developer Guide

### PR DESCRIPTION
**Pull request by outoftardis**
# Description

API follows the same structure as Developer Guide. Examples. usage examples, navigation tables and introductions are shared between DevGuide and API.

Output: https://outoftardis.github.io/daal/

### CODE REVIEW

**Review by averbukh — APPROVED** [review]

**Comment by napetrov** [comment]
CI failed due to "error" word in commit message.  Also there is conflict now

**Review by napetrov — APPROVED** [review]

**Comment by outoftardis** [comment]
@napetrov  please confirm that my changes do not cause precommit to fail

**Pull request merged**
