### PR TITLE
[DOC] Fixed wording in docs

### PR DESCRIPTION
**Pull request by outoftardis**
# Description

- Small fixes in wording.
- Fix in css for coding guidelines

### CODE REVIEW

**Review by napetrov — APPROVED** [review]

**Comment by outoftardis** [comment]
image

**Review by averbukh — APPROVED** [review]

**Comment by outoftardis** [comment]
@napetrov the errors in CI do not appear to be caused by my changes, is it ok to merge?

**Comment by napetrov** [comment]
it's ok to merge

**Pull request merged**
