### PR TITLE
Rename libs: daal -> onedal

### PR DESCRIPTION
**Pull request by rlnx**
<table>
<tr>
<td>

Linux

</td>
<td>

Windows

</td>
</tr>

<tr>
<td>
<image width="300" src="https://user-images.githubusercontent.com/5404873/86520614-2cb56280-be4f-11ea-9287-03f7ea92546d.png">
</image>
</td>
<td>
<image width="300" src="https://user-images.githubusercontent.com/5404873/86522236-79a33400-be63-11ea-8bc5-9c4b9768a76a.png">
</image>
</td>
</tr>
</table>

### CODE REVIEW

**Comment by teabagk7** [comment]
I think this will affect the mkl fpk update process.
We definitely should discuss it.

**Comment by rlnx** [comment]
Talked with @teabagk7, there are not problems with FPK update process.

**Comment by rlnx** [comment]
/intelci: restart
set infra_branch=dev/risrafil-rename-libs

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-rename-libs

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-rename-libs

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-rename-libs

**Comment by rlnx** [comment]
/intelci: run
set infra_branch=dev/risrafil-rename-libs

**Pull request merged**
