### PR TITLE
Cmake improvements

### PR DESCRIPTION
**Pull request by napetrov**
# Description
Adding CMake improvements based on - https://github.com/oneapi-src/oneDAL/issues/2110

### CODE REVIEW

**Comment by napetrov** [comment]
/intelci: run
set infra_branch=dev/napetrov_cmake

**Review by KulikovNikita — APPROVED** [review]

**Comment by emmenlau** [comment]
Awesome guys, thanks!!!

**Comment by napetrov** [comment]
> Awesome guys, thanks!!!

Thanks for your suggestions!

**Pull request merged**
